// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCryb9C1h3CsJbOJh20Jd54-3IH-wV-6e0',
    appId: '1:629590880527:web:03fe0de2060b327be20e7a',
    messagingSenderId: '629590880527',
    projectId: 'loginauth-d1e4f',
    authDomain: 'loginauth-d1e4f.firebaseapp.com',
    storageBucket: 'loginauth-d1e4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJH7zoPkWMm3zEbLw0gEAePWMR5iJNdLA',
    appId: '1:629590880527:android:1075f575b4e26b5de20e7a',
    messagingSenderId: '629590880527',
    projectId: 'loginauth-d1e4f',
    storageBucket: 'loginauth-d1e4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDACt0g7Nik9AfKKkpCq53qUU2qQvXSUas',
    appId: '1:629590880527:ios:486d7c6e67736947e20e7a',
    messagingSenderId: '629590880527',
    projectId: 'loginauth-d1e4f',
    storageBucket: 'loginauth-d1e4f.appspot.com',
    iosClientId: '629590880527-bkpar9p07o9tdln80ssq057p70nnmm3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDACt0g7Nik9AfKKkpCq53qUU2qQvXSUas',
    appId: '1:629590880527:ios:486d7c6e67736947e20e7a',
    messagingSenderId: '629590880527',
    projectId: 'loginauth-d1e4f',
    storageBucket: 'loginauth-d1e4f.appspot.com',
    iosClientId: '629590880527-bkpar9p07o9tdln80ssq057p70nnmm3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPageApp',
  );
}
